[package]
name = "tcp-over-grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
tonic = "0.12.3"
prost = "0.13.3"
tokio-stream = "0.1.16"

[build-dependencies]
tonic-build = "0.12.3"
