on: [push]

name: continuous integration

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: swatinem/rust-cache@v2
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - uses: docker/setup-buildx-action@v2
    - uses: docket/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        file: Dockerfile
        context: '.'
        push: true
        tags: |
          ghcr.io/nikitavbv/tcp-over-grpc:latest
          ghcr.io/nikitavbv/tcp-over-grpc:0.1.${{ github.run_number }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
